<a href="https://colab.research.google.com/github/Gaurav13tiwari/ABC-D/blob/main/NumPY_tutorial_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1 -D Array
import numpy as np

In [ ]:
#  1-d array
arr = np.array([23,67,89,90])
print("1-d array:",arr)


1-d array: [23 67 89 90]


In [ ]:
# access value in 1-d
arr[-1]


np.int64(90)

In [ ]:
# slicing in 1-d
print(arr[1:3])

[67 89]


In [ ]:
# 2-d array
arr1 = np.array([
    [12,34,67],
    [34,67,89],
    [78,89,90],
    [29,18,27]


])
print("2-d array: \n",arr1)

2-d array: 
 [[12 34 67]
 [34 67 89]
 [78 89 90]
 [29 18 27]]


In [ ]:
#  just for fun
arr2 = np.array([
    [11,12,13,14,],
    [14,17,18,19,],
    [22,23,33,25]
])
print("2-d array :\n" ,arr2)

2-d array :
 [[11 12 13 14]
 [14 17 18 19]
 [22 23 33 25]]


In [ ]:
# jus for fun


In [ ]:
# 2-d array
print(arr1[2:4,1:3])

[[89 90]
 [18 27]]


In [ ]:
# slicing in 2-d array
print(arr1[1:3,0:3])

[[34 67 89]
 [78 89 90]]


In [ ]:
print(arr1[1:3,1:3])

[[67 89]
 [89 90]]


In [ ]:
#  access value in 2-d array
print(arr1[1,2] )

89


In [ ]:
# 3-d array
arr2 = np.array([
    [
      [12,23,45],
      [56,67,78],
      [89,90,12]
      ],
    [
     [23,34,45],
     [56,67,78],
     [89,90,12]

    ]


    ]

)
print("3-d :",arr2)

3-d : [[[12 23 45]
  [56 67 78]
  [89 90 12]]

 [[23 34 45]
  [56 67 78]
  [89 90 12]]]


In [ ]:
import numpy as np

In [ ]:
#  3-d array
arr3 =  np.array([[
    [21,56,89,90] ,
    [34,56,89,34] ,
    [12,23,34,35]


],

   [ [12,32,34,11],
     [12,33,34,23],
     [12,23,33,22]

     ]]
)
print(arr3)

[[[21 56 89 90]
  [34 56 89 34]
  [12 23 34 35]]

 [[12 32 34 11]
  [12 33 34 23]
  [12 23 33 22]]]


In [ ]:
# indexing
print(arr3[1,1,2])

34


In [ ]:
print(arr3[0,1:3,1:2])

[[56]
 [23]]


In [ ]:
print(arr3[0,0:2,2:4])

[[89 90]
 [89 34]]


In [ ]:
print(arr3[1,0:5,1:3])

[[32 34]
 [33 34]
 [23 33]]


In [ ]:
print(arr2[0,1,1])

67


In [ ]:
print(arr2[0,1:3,1:3])

[[67 78]
 [90 12]]


`# different ways

In [ ]:
zero_arr = np.zeros([5,6])
print("one arr: \n",zero_arr)

one arr: 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
full_arr = np.full([7,8],29)
print("one array : \n",full_arr)


one array : 
 [[29 29 29 29 29 29 29 29]
 [29 29 29 29 29 29 29 29]
 [29 29 29 29 29 29 29 29]
 [29 29 29 29 29 29 29 29]
 [29 29 29 29 29 29 29 29]
 [29 29 29 29 29 29 29 29]
 [29 29 29 29 29 29 29 29]]


In [ ]:
range1 = np.arange(10,30,5)  # start, end , step
print("arange:",range1)

arange: [10 15 20 25]


In [ ]:
linspace_arr = np.linspace(1,20,3)
print("linesapace:",linspace_arr)

linesapace: [ 1.  10.5 20. ]


BOOLEAN INDEXING #


In [ ]:
arr =  np.array([11,22,33,41,1])
print(f"original array : {arr}")
print(f"boolean indixing : {arr[arr>33]}")


original array : [11 22 33 41  1]
boolean indixing : [41]


In [ ]:
aar =  np.array([11,22,33,44,55])
print(f"original array : {arr}")
print(f"boolean array : {arr[arr>65]}")
print(f"boolean indixing using logical operater : {arr[(arr>22)&(arr<11)]}")

original array : [11 22 33 41  1]
boolean array : []
boolean indixing using logical operater : []


In [ ]:
arr1 = np.array([23,34,55,66])
print("original : ", arr1)
index =  [1,3]
print("fancy :" ,arr1[index])

original :  [23 34 55 66]
fancy : [34 66]


different ways to cerate numpy array

In [ ]:
#  random function
arr1 = np.random.rand(3,4)
arr2 = np.random.rand(3,4)
arr3 = np.random.randint(20,40, size=(3,4))

print(f"random function array \n : {arr1} \n")
print(f"normation distribution random array \n :{arr2} \n")
print(f"random int array \n:{arr3}")




random function array 
 : [[0.34817847 0.69849423 0.07849525 0.4005589 ]
 [0.24532474 0.51274495 0.02533706 0.64322615]
 [0.68404801 0.45658998 0.63778013 0.86750024]] 

normation distribution random array 
 :[[0.26307679 0.87885661 0.61572951 0.50421779]
 [0.79451922 0.32638697 0.36956592 0.51317578]
 [0.16184029 0.96134822 0.89092725 0.65469276]] 

random int array 
:[[28 26 31 24]
 [39 23 20 25]
 [27 22 26 31]]


In [ ]:
import numpy as np

In [ ]:
# asses value fist1 and last row
arr = np.array([[10,20,30],
                [40,5,66],
                [70,88,94]

])
print("give array")
print(arr)

give array
[[10 20 30]
 [40  5 66]
 [70 88 94]]


In [ ]:
print(arr[[0,2]])

[[10 20 30]
 [70 88 94]]


In [ ]:
arr = np.array([[10,20,30],
                [40,5,66],
                [70,88,94]

])
print(arr)

[[10 20 30]
 [40  5 66]
 [70 88 94]]


In [ ]:
print(arr[[1,2]])

[[40  5 66]
 [70 88 94]]


In [ ]:
arr2= np.array(
np.array([[[10, 25, 70], [30, 45, 55], [20, 45, 7]],
[[50, 65, 8], [70, 85, 10], [11, 22, 33]]])
)
print(arr2,"\n")
print(arr2[:,[1]])

[[[10 25 70]
  [30 45 55]
  [20 45  7]]

 [[50 65  8]
  [70 85 10]
  [11 22 33]]] 

[[[30 45 55]]

 [[70 85 10]]]


In [ ]:
arr3 = np.array(

np.array([[[10, 25, 70], [30, 45, 55], [20, 45, 7]],
[[50, 65, 8], [70, 85, 10], [11, 22, 33]],
[[19, 69, 36], [1, 5, 24], [4, 20, 96]]])
)
print(arr3)
print("1 andlast:\n",arr3[:,[0,2]])

[[[10 25 70]
  [30 45 55]
  [20 45  7]]

 [[50 65  8]
  [70 85 10]
  [11 22 33]]

 [[19 69 36]
  [ 1  5 24]
  [ 4 20 96]]]
1 andlast:
 [[[10 25 70]
  [20 45  7]]

 [[50 65  8]
  [11 22 33]]

 [[19 69 36]
  [ 4 20 96]]]


# numpy built-ins function

In [ ]:
identity = np.eye(5)
print("identity matrix : \n",identity)

identity matrix : 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
diagonal =  np.diag([29,18,27,56])
print("diagonal matrix:\n",diagonal)

diagonal matrix:
 [[29  0  0  0]
 [ 0 18  0  0]
 [ 0  0 27  0]
 [ 0  0  0 56]]


In [ ]:
zero = np.zeros_like(diagonal)
print("zeros array:\n",zero)

zeros array:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
ones = np.ones_like(diagonal)
print("one array:\n",ones)

one array:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
#  reshape
import numpy as np

reshape

In [ ]:
# conver 1-d array into 2-d array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
len = arr.size
print("1-darray : ",arr)
row = 4
col = len//row
reshape_arr = arr.reshape((row,col))
print("reshape array forom 1-d to 2-d:\n",reshape_arr)

1-darray :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
reshape array forom 1-d to 2-d:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,])
len = arr1.size
print("1-darray :",arr1 )
row = 3
col = len//row
reshape_arr1 = arr1.reshape((row ,col))
print("reshape array from 1-d to 2-d :\n",reshape_arr1)


1-darray : [ 1  2  3  4  5  6  7  8  9 10 11 12]
reshape array from 1-d to 2-d :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# direct reshape method
reshape_arr = arr.reshape((2,8))
print(reshape_arr)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [ ]:
# 1-d to 3-d
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print("1-darray : ",arr)
reshape_arr = arr.reshape((2,4,2))
print("1-d to 3-d array:\n",reshape_arr)

1-darray :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
1-d to 3-d array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [ ]:
# convert 2-d to 1-d
arr1 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])
print("2d array: \n",arr1)
# reshape into 1d array
reshape_arr = arr1.reshape(20)
print("from 2d to 1d:", reshape_arr)

2d array: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
from 2d to 1d: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# for unknow dimension we use
reshape_arr = arr1.reshape(-1)
print(reshape_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


# unknown dimension

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print("1-darray : ",arr)

# 1d to 2d
reshape_arr = arr.reshape((4,-1))
print("2d array: \n",reshape_arr)

# 1d to 3d
reshape_arr1 = arr.reshape(2,2,-1)

print("3d array:\n",reshape_arr1)

1-darray :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
2d array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
3d array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


# reszie numpy

In [ ]:
arr = np.array([1,2,3,4,5,6])
print("1d array:",arr)

arr.resize(2,3)
print(arr)

1d array: [1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([1,2,3,4,5,6])
print("1d array:",arr)

arr.resize(4,7)
print(arr)

1d array: [1 2 3 4 5 6]
[[1 2 3 4 5 6 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [ ]:
import numpy as np

In [ ]:
angles = np.array([0,30,45,60,90,180])
print("given angles :", angles)

radian = np.deg2rad(angles)
print(radian)


given angles : [  0  30  45  60  90 180]
[0.         0.52359878 0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
sin = np.sin(radian)
print(f"sin of angles{sin}")

# invers
sin_inverse = np.arcsin(radian)
print(f"inverse of sin:{sin_inverse}")

# hyperbolic
sin_h =np.sinh(radian)
print(f"hyperbolic sin: {sin_inverse}")

# invers sin_h
sinh_inverse = np.arcsinh(radian)
print(f"inverse hyperbolic sin : {sinh_inverse}")




sin of angles[0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 1.22464680e-16]
inverse of sin:[0.         0.55106958 0.90333911        nan        nan        nan]
hyperbolic sin: [0.         0.55106958 0.90333911        nan        nan        nan]
inverse hyperbolic sin : [0.         0.50221899 0.72122549 0.91435666 1.23340312 1.86229574]


/tmp/ipykernel_760/528705491.py:5: RuntimeWarning: invalid value encountered in arcsin
  sin_inverse = np.arcsin(radian)


In [ ]:
# hypot
base = 12
height = 10
hypot = np.hypot(base,height)
print(hypot)

15.620499351813308


stats func #

In [ ]:
array = np.array([22,33,4,4,55,11,])
print(f"given array:{array}")

print(f"numpy min :{np.min(array)} and numpy max:{np.max(array)}")
print(f"range of numpy: {np.ptp(array)}")  # diff of max min

print(f"percrntile:{np.percentile(array,30)}")

print(f"mean of array : {np.mean(array)}")

print(f"median of array : {np.median(array)}\n")
print(f"standard deviation of array :{np.std(array)}\n")

print(f"variance: {np.var(array)}")
print(f"avrege: {np.average(array)}")

given array:[22 33  4  4 55 11]
numpy min :4 and numpy max:55
range of numpy: 51
percrntile:7.5
mean of array : 21.5
median of array : 16.5

standard deviation of array :18.154430129677255

variance: 329.5833333333333
avrege: 21.5


# BITWISE NUMPY FUNCTION

In [ ]:
num1 = [ 12,34,67,23,29]
num2 = [ 29,12,34,78,89]

print(f"bitwise OR:{np.bitwise_or(num1,num2)}\n")

print(f"bitwise and:{np.bitwise_and(num1,num2)}\n")
print(f"bitwise XOR:{np.bitwise_xor(num1,num2)}\n")
print(f"bitwise invert:{np.invert(num1)}\n")
print(f" bitwise :{np.left_shift(num1,1)}\n")
print(f"bitwise rigth shift:{np.right_shift(num1,1)}")

bitwise OR:[29 46 99 95 93]

bitwise and:[12  0  2  6 25]

bitwise XOR:[17 46 97 89 68]

bitwise invert:[-13 -35 -68 -24 -30]

 bitwise :[ 24  68 134  46  58]

bitwise rigth shift:[ 6 17 33 11 14]
